template = "https://github.com/giellalt/template-lang-und"
rev_id = 270
template_sha = "a0e776e00408c682c6560029f0fded3c700e0e63"

[replacements]
__GLOTTOLOG_ID__ = "cher1273"
__REPO__ = "lang-chr"
__UND2C__ = "chr"
__UNDEFINED__ = "Cherokee"
__UND__ = "chr"
